src/Shared/EditorMapLayer.h

The class does not exist, so there's no need to keep this.

Remove unused forward declaration for missing class `MapCSS`

---

src/Shared/OsmMapData.h
src/Shared/OsmMapData.m

Since the property is is only accessed in the implementation file, we don't need
to have it publicly available.
In addition, doing this gets rid of a lot of warnings that were caused by the
`nonnull`, and the rest of the (public) interface lacking the nullability specifiers.
This is the MVP approach to silence those warnings. Ideally, we would
audit the whole file for nullability, but that takes more time.

Remove a lot of warnings by moving property `previousDiscardDate` to private interface

---

src/iOS/Go Map!!.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

As per the [Xcode Release Notes][1]:
> Xcode 9.3 adds a new IDEWorkspaceChecks.plist file to a workspace's shared data,
> to store the state of necessary workspace checks.
> Committing this file to source control will prevent unnecessary rerunning
> of those checks for each user opening the workspace. (37293167)
[1]: https://developer.apple.com/library/archive/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-DontLinkElementID_31

Add IDEWorkspaceChecks.plist

---

src/Shared/VectorMath.h
src/Shared/iosapi.h
src/iOS/Go Map!!.xcodeproj/project.pbxproj

With these two build settings fixed, Xcode builds successfully when adding Swift files.
These changes don't add any new functionality. Rather, they allow developers to potentially start developing with Swift 5. 😎

Fix build settings for Swift

---

src/iOS/Base.lproj/MainStoryboard.storyboard

This replaces the "inline" links with complete URLs in braces. By enabling the "Link" data detector, the links can be tapped, which opens them in Safari.

Fix: Make links in "Help" view controller tapable

---

src/Shared/MapView.m

This branch adds an "Open Settings" action to the alert that is presented when the app doesn't have the permission to access the device location. Choosing this action opens the Settings page of the application, allowing the user to easily change the location permission.
Here's a screenshot of the alert controller in action:

Enable users to "Open Settings" when location access is denied

---

src/Shared/MapView.m

This makes sure that the button is perfectly round and doesn't look cut off. Comparison:

Fix: Use the help button's size to determine its corner radius

---

src/Shared/MapView.m

By setting this "magic number" corner radius, the black corners are no longer visible.
Visual comparison:

Fix: Use proper `cornerRadius` for edit control to remove black corners

---

src/iOS/POIAllTagsViewController.m

This branch makes sure to only show the "Relations" section in the "Node tags" view if there were actually any relations.

Fix: Hide empty "Relations" section in tag list

---

src/iOS/POIAllTagsViewController.m

This dismisses the keyboard a little bit earlier, making sure it is no longer visible when the user is back on the map.

Fix: End editing when tapping "Cancel" bar button item in the "Node tags"

---

src/iOS/Base.lproj/MainStoryboard.storyboard
src/iOS/POIAttributesViewController.m

There's no need to have the user interact with these values.
Disabling user interaction furthermore improves the usability, since the user
doesn't need to tap on the disclosure indicator anymore, but can use the whole cell.

Fix: Disable user interaction for `value` text field of node attributes

---

src/Shared/MapView.m

This branch will display an `UIAlertController` asking the user to allow camera access when attempting to execute the `ACTION_HEIGHT`:
This prevents a black `HeightViewController` from being presented.

Handle missing camera permission when measuring height

---

src/iOS/POITabBarController.m

This prevents a bug that, one after another, removes all tab bar items as soon as the tab bar becomes visible again.
It's wrong to _always remove the last_. Instead, this commit makes sure to only remove view controllers from the tab bar that are `UINavigationController`s that contain the `POIAttributesViewController`.

Fix: Only hide `POIAttributesViewController`, not the other view controllers

---

src/iOS/Go Map!!-Info.plist
src/iOS/Go Map!!.xcodeproj/project.pbxproj

With this branch, builds with the DEBUG configuration will have the display name "Go Map!! Debug", whereas builds with RELEASE configuration will continue to use "Go Map!!".
This helps developers to identify the configuration of the app they are running, and it is especially helpful if you have both the App Store version as well as a debug version installed at the same time.

Feature: Use different display name for DEBUG builds

---

src/iOS/NominatumViewController.m

This makes sure that the keyboard is no longer visible when back on the map.

Fix: Dismiss the keyboard along with the "Search for Location" view controller

---

src/iOS/Base.lproj/MainStoryboard.storyboard

This branch makes sure to use a proper `UINavigationController` instance when presenting the view controllers for
- "Search for Location" and
- "Note"
Furthermore, it uses a _User Defined Runtime Attribute_ to set the `backgroundColor` of the map navigation controller's view to white in order to avoid a dark top-right corner when pushing the settings.

Fix: Fix presentation of navigation bars and modal view controllers

---

src/iOS/Base.lproj/MainStoryboard.storyboard

Otherwise, there's a color difference between the status bar and the navigation bar.
Old:
New:

Fix: Use `UINavigationController` when presenting the Bing metadata

---

src/Shared/CommonTagList.m
src/iOS/Go Map!!-Bridging-Header.h
src/iOS/Go Map!!.xcodeproj/project.pbxproj
src/iOS/GoMapTests/CommonTagKeyTestCase.swift
src/iOS/GoMapTests/Vendor/Require.swift

Fix: Use localized presets for placeholder

---

src/Shared/OsmMapData.h
src/Shared/OsmMapData.m
src/iOS/Base.lproj/MainStoryboard.storyboard
src/iOS/Extensions/LoginViewController.swift
src/iOS/Go Map!!-Bridging-Header.h
src/iOS/Go Map!!.xcodeproj/project.pbxproj
src/iOS/Go Map!!.xcodeproj/xcshareddata/xcschemes/GoMapTests.xcscheme
src/iOS/GoMapTests/Helpers/XCTestCase+UserDefaults.swift
src/iOS/GoMapTests/OSMMapDataTestCase.swift
src/iOS/LoginViewController.h
src/iOS/LoginViewController.m

This branch fixes #212.
There are a couple of changes:
1. Spell checking is now disabled for the "username" field
2. Only _verified_ (= correct) credentials are stored in the `KeyChain`
3. When changing the server and providing an URL without `/` as the suffix, the app only adds a single `/` to it - not two
4. Improve error handling for when the server does not respond with a numeric ID while attempting to create a changeset

Fix: "unsupported url" error message during upload

---

src/Shared/OsmObjects.m

I changed the functionality of `MergeTags` to mimic JOSM's `Shift+R` command when pasting tags. 
References #169

Paste Functionality

---

src/Shared/EditorMapLayer.m

By setting `masksToBounds`, the `cornerRadius` is applied properly. This makes sure they match the other (already rounded) icons.
Before:
After:

Fix corner radius presentation of map icon layers

---

src/Shared/OsmMapData.h
src/Shared/OsmMapData.m

This branch makes sure that the designated initializer `initWithUserDefaults:` is called, and that the initializer chain is being kept. Otherwise, things that happen in the designated initializer will only _sometimes_ being invoked.
This fixes a crash for me when `OsmMapData` was created with `new` (= `alloc init`), which did not call the designated initializer (`initWithUserDefaults:`), which resulted in un-initialized instance variables.

Fix initialization of OsmMapData

---

src/Shared/OsmMapData.m

With 3de0260, I have introduced a change where the object that had just been decoded would be overwritten with `[self init]`. This results in the database entries not showing up on the map.
1. Open the app
2. Add a new node
3. Select a type (any will do) and hit "Save"
4. Hard-close the app
5. Open the app again
**Expected behaviour:** The new node persisted the restart and is visible on the map.
**Observed behaviour:** The new node is not visible on the map.
Sorry for introducing this, my bad! I'll try to remember to add unit tests the next time I introduce such changes.

Fix: OsmMapData is not decoded properly

---

src/iOS/Base.lproj/MainStoryboard.storyboard
src/iOS/NominatumViewController.m

This branch allows for the cells in the location search to have unlimited number of lines (`0`). Longer text is no longer truncated:
Besides fixing #245, this improves the Accessibility of the app when using larger text.

Fix: Location search results are truncated

---

src/iOS/Base.lproj/MainStoryboard.storyboard

While testing the app with TestFlight, I was experiencing
the same crash as described in this [Stack Overflow post][1],
so I removed the item from the storyboard.
I've created another TestFlight build with this fix, and was no longer able to reproduce the crash.
For testing, just open the app and long-tap on the "Location" arrow in the bottom left corner of the app, in the tab bar.
[1]: https://stackoverflow.com/q/57819165

Fix: Remove `UISearchDisplayController` from storyboard

---

src/iOS/Go Map!!.xcodeproj/project.pbxproj

Minor update to remove deprecated legacy language settings at @wtimme’s [suggestion](https://github.com/wtimme/OSM-Completionist/pull/31#issuecomment-571296768).

Upgrade to modern localization

---

src/iOS/MapViewController.m

Apparently, when tapping a note on the map view, the view
controller that displays the note's comments is presented
inside a `UINavigationController`.
This fixes #254.

Fix handling of notes when presented in navigation controller

---

src/Shared/EditorMapLayer.m
src/iOS/GeekbenchScoreProvider.h
src/iOS/GeekbenchScoreProvider.m
src/iOS/Go Map!!.xcodeproj/project.pbxproj

This branch moves the method that determines the Geekbench score from `EditorMapLayer` to a dedicated file.
The goal of these changes is to reduce the number of lines in `EditorMapLayer` so that it is easier to read and maintain. Furthermore, by having this code in a dedicated file, it can be used in other places, e. g. new layers.

Refactoring: Move Geekbench score to a dedicated file

---

src/iOS/FpsLabel.m

With this branch, I remove a debug log from the `FpsLabel` that is printed whenever the map moves.
I like to monitor the FPS of the map, so I have the label visible at all times. That's when I noticed that the log was being filled with the message "frame". This seems to make the Simulator run slower, and the log is barely usable anymore.

Remove debug `NSLog` from `FpsLabel`

---

src/Shared/EditorMapLayer.h
src/Shared/EditorMapLayer.m
src/Shared/MapView.m

This branch improves the interface of `EditorMapLayer` by adding type-hints to the collections, which makes it easier for both Objective-C and Swift to work with them.
In addition, it makes the code much easier to understand, since types don't need to be guessed anymore.

Refactoring: Improve interface of `EditorMapLayer`

---

src/Shared/Database.h
src/Shared/Database.m
src/Shared/OsmMapData.m

This branch improves the interface of `Database` by adding type-hints to the collections, which makes it easier for both Objective-C and Swift to work with them.
In addition, it makes the code much easier to understand, since types don't need to be guessed anymore.

Refactoring: Improve interface of `Database`

---

src/Shared/MapView.m
src/Shared/OsmMapData+Edit.m
src/Shared/OsmMapData.h
src/Shared/OsmMapData.m
src/iOS/OSMModels/OsmBaseObject.h
src/iOS/OSMModels/OsmBaseObject.m
src/iOS/POIAllTagsViewController.m
src/iOS/POICommonTagsViewController.m
src/iOS/TurnRestrictController.m

This branch adds type-hinting to the collections of `OsmMapData`'s public interface. It also follows up on the hints by adding them to the callers.
The goal of this pull request is to improve the interoperability with Swift, as well as to improve the readability of the code.

Refactoring: Add type hinting to `OsmMapData`

---

src/iOS/Base.lproj/MainStoryboard.storyboard
src/iOS/NotesTableViewController.m

This branch resolves #279 by using system-provided colors instead of custom ones for the "Notes" view.
Regular (light):
Dark Mode:

Bugfix: Fix Dark Mode appearance of Notes

---

src/Shared/EditorMapLayer.m

This branch implements a couple of tint colors for the icons (#277). It makes use of the existing method `defaultColorForObject:`.

Feature: Use `defaultColorForObject:` for tinting node icons

---

src/iOS/Base.lproj/MainStoryboard.storyboard
src/iOS/NearbyMappersViewController.m
src/iOS/POIAttributesViewController.m

This should fix #275 
The `POIAttributesViewController` and the `NearbyMappersViewController` now use a `SFSafariViewController` instead of the custom `WebPageViewController`. This includes also a navigation change, the `SFSafariViewControllers` are now displayed modal (not pushed to the navigation stack). Otherwise the `Done` button on the `SFSafariViewController` would dismiss the whole navigation stack.
If this isn't ok, we have to implement our own `WebPageViewController`, and handle the whole sharing code ourselves.
If this PR is ok, we can think about removing the `WebPageViewController` also in code. The `MapView` also uses this `ViewController`.

Switch from WebPageViewController to SFSafariViewController

---

src/Shared/EditorMapLayer.m

Feature: Use `#127A38` as the icon color for "natural=tree"

---

src/iOS/POICommonTagsViewController.m

By removing the static color that is set in code, the color is controlled by the system and adapts to Dark Mode.

Fix label color for Dark Mode in `POICommonTagsViewController`

---

src/Shared/EditorMapLayer.m

This branch changes the white box behind nodes on the map, making them appear in a circle.

Feature: Use circle for nodes on the map

---

src/Shared/AerialList.m

iD is switching to its own thing, so the Editor Layer Index will inevitably receive less updates. The JOSM index already has more and more up-to-date layers. Both indexes are under the same CC-BY-SA license.

Use the JOSM layer index

---

src/iOS/POICommonTagsViewController.m

This branch fixes #282 by only attempting to select the "name" field for presets with the tag "shop"; not for "amenity" ones.
In addition, I moved the code for displaying the keyboard to `viewDidAppear:`, which make sure that it is displayed _after_ the "POI Type" view controller was dismissed.

Fix: Flickering of panel after selecting preset

---

src/iOS/GoMapTests/CommonTagKeyTestCase.swift

This removes four warnings that were displayed for the `GoMapTests` target.

Cleanup: Get rid of warnings by using `require()` for unwrapping of optionals

---

src/iOS/Storyboards/Base.lproj/Settings.storyboard

This adds the `username` and `password` content types to the text inputs in the login view.
I haven't looked into whats necessary to configure the associated domains to directly show the correct entry, but even without, this is still an improvement.

Support password AutoFill

---

src/iOS/POIFeaturePickerViewController.m

This branch resolves an issue where, when `AppDelegate.shared.mapView.countryCodeForLocation` was `nil`, the footer text of the POI feature picker would read "Result for (null) ((null))".

Fix: Don't display a footer text that says "Results for null (null)"

---

src/iOS/Storyboards/Base.lproj/POI.storyboard

This change in layout constraints allows the mapper to tap the whole cell, instead of requiring them to tap exactly the blue button text.

Make the whole "Customize Presets" cell tappable

---

src/Shared/EditorMapLayer.m
src/Shared/LayerProperties.h
src/Shared/LayerProperties.m
src/Shared/OSMModels/OsmBaseObject.h

This branch adds type-hinting to the arrays that contain `CALayer` subclasses that are expected to have `properties`.
By using a protocol and the base class `CALayer`, we can now tell that an array contains instances of `CALayer<LayerPropertiesProviding>`.

Add type-hinting for arrays that contain `CALayer`s with `properties`

---

src/Shared/CurvedTextLayer.swift
src/iOS/GoMapTests/Mocks/MeasureDirectionViewModelDelegateMock.swift

This branch removes two warnings that were displayed in Xcode when building/testing/running the `master` branch.

Refactoring: Remove warnings

---

src/iOS/Go Map!!-Info.plist

This partially reverts commit c63e3523aed25b28241d61c32291999974041117.

Re-enable "Go Map!! Debug" as the display name for DEBUG builds

---

.gitignore
README.md
src/iOS/Go Map!!-Info.plist
src/iOS/Go Map!!.xcodeproj/project.pbxproj
src/iOS/Go Map!!.xcodeproj/xcshareddata/xcschemes/Go Map!!.xcscheme
src/iOS/GoMapTests/Info.plist
src/iOS/GoMapUITests/Info.plist
src/iOS/fastlane/Fastfile
src/iOS/fastlane/README.md

This pull request prepares the fully automated release process (cp. #426) by adding a _fastlane_ lane that allows for the Beta to be tested, build and signed automatically.
As per the updated README:
> In order to release a new Beta to the TestFlight testers, run
> 
>      % MATCH_REPO=<GIT_REPOSITORY_URL> \
>        MATCH_PASSWORD=<MATCH_PASSWORD> \
>        FASTLANE_TEAM_ID=<APPLE_DEVELOPER_TEAM_ID> \
>        FASTLANE_USER=<APP_STORE_CONNECT_EMAIL> \
>        FASTLANE_ITC_TEAM_ID=<APP_STORE_CONNECT_TEAM_ID> \
>        bundle exec fastlane beta

Setup fastlane for Beta distribution

---

src/iOS/fastlane/Fastfile

This gets rid of the annoying popup that @bryceco [reported](https://github.com/bryceco/GoMap/issues/426#issuecomment-692289477) by deleting the private Keychain after creating the Beta build.

Delete private keychain after creating the beta

---

src/iOS/GoMapTests/PresetKeyTagCase.swift

With the conversion of `PresetKeyTag`, the initializer no longer returns an optional, removing the need to use `.require()` here.
Side note: We might have discovered this earlier if we had continuous integration in place (#420).

Fix failing `PresetKeyTagCase`

---

src/iOS/MainViewController.m

This fixes the help button at the top left corner of the map, which should be a round circle.

Let the help button on the map be a full circle

---

src/iOS/Storyboards/Base.lproj/MainStoryboard.storyboard

With iOS 15 the nominatim search view controller navigation bar had a transparent background:
This is how it looks now on iOS 15:

Fixed transparent background in nominatim search

---

CHANGELOG.md

This relates to #436 and eventually aims to 'fix' the issue.
I made screenshots from the 'Version history' from the [App Store].
These screenshots were then stitched together with successive pairwise stitching in [Fiji].
This resulting image was then piped through `tesseract image.tif history` and copied to CHANGELOG.md for an initial version of the file.
Subsequent commits aim at cleaning up the file, making it more markdowns and proof-reading it.
[App Store]: https://apps.apple.com/ch/app/go-map/id592990211?l=en
[Fiji]: https://imagej.net/plugins/image-stitching#pairwise-stitching

Initial version of changelog

---

src/Shared/OSMModels/OsmBaseObject.swift

fixes #611 
after fix applied, `name:en` or other `name:*` tags will be used if there is no `name` tag

add fallback to other name:* tags for friendly name

---

src/iOS/Go Map!!-Info.plist

Use Default handler rank so that users
with multiple apps that can open gpx files
can still use them easily. Default handler
rank makes it easy to open any GPX with
any app that supports it. Owner LSHandlerRank
is problematic because users must go through
a convoluted set of steps to open GPX files
in another app.

use Default LSHandlerRank for gpx files

---

src/iOS/POI/KeyValueTableCell.swift

This PR enables the new `TelephoneToolbar` for the `KeyValueTableCell` which was discussed. See #511

Enable TelephoneToolbar for KeyValueTableCell

---

src/Shared/MapTransform.swift
src/Shared/MapView.swift
src/iOS/Base.lproj/MainStoryboard.storyboard
src/iOS/CustomViews/RulerView.swift

Closes #726
The initial unit system is set from the user's system locale. pressing on the bar changes the unit (which in my opinion is a bad idea, it should be a setting because users are going to press it accidentally and then have no idea why it changed or how to change it back, just as you didn't know that clicking the scale bar on iD changes the units). changing your locale in system settings also changes the unit, regardless of what it was set to before.
I also changed it to use monospace numbers so that the "m" doesn't jitter around as much as you zoom. ~~it still jitters when you go between adding/removing the decimal point and more or less numbers.~~ and made it always use at least 3 digits.
~~I also removed the black line and left-aligned the text~~

Show only one distance unit in ruler

---

README.md
src/iOS/DisplaySettings/Base.lproj/Display.storyboard

Enable Filters → Filters
Enable Rotation → Map Rotation
It doesn't make sense to have the word "Enable" next to an on/off switch. The switch already implies that the given thing is enabled/disabled.

Remove the word "Enable" from options

---

src/Shared/EditorLayer/EditorMapLayer.swift
src/Shared/EditorLayer/RenderInfo.swift
src/Shared/EditorLayer/iD/Theme.swift
src/Shared/EditorLayer/iD/extract.py

I updated extract.py to extract [stroke-opacity values](https://github.com/openstreetmap/iD/blob/14d76e4445512094d68580964c5abf08ed9f9a51/css/50_misc.css#L350) from the css and re-ran it on the latest commit to iD to update the theme.
I also changed `lineJoin` to `.round` to match iD.
left is `highway=path`, right is `highway=path` & `tunnel=yes`:
iD for comparison:

Make tunnels slightly transparent

---

src/iOS/Localizable.xcstrings
src/iOS/Panoramax.swift

Submitting pull request to address issue #846 by changing the `captureAndUploadPhotograph` function in `Panoramax.swift` to include `sourceType=.photoLibrary`:
```
@IBAction
func captureAndUploadPhotograph(_ sender: Any) {
let alert = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
alert.addAction(UIAlertAction(title: NSLocalizedString("Take Photo", comment: ""), style: .default, handler: { _ in
let vc = UIImagePickerController()
vc.sourceType = .camera
vc.allowsEditing = false
vc.delegate = self
self.present(vc, animated: true)
}))
alert.addAction(UIAlertAction(title: NSLocalizedString("Upload Photo", comment: ""), style: .default, handler: { _ in
let vc = UIImagePickerController()
vc.sourceType = .photoLibrary
vc.allowsEditing = false
vc.delegate = self …
```

Adding option to upload a photo to Panoramax in addition to taking a photo
